// Code generated by "stringer -type=comparisonPosition"; DO NOT EDIT.

package indexset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[comparisonPositionUnknown-0]
	_ = x[comparisonPositionLeft-1]
	_ = x[comparisonPositionRight-2]
	_ = x[comparisonPositionOverlap-3]
}

const _comparisonPosition_name = "comparisonPositionUnknowncomparisonPositionLeftcomparisonPositionRightcomparisonPositionOverlap"

var _comparisonPosition_index = [...]uint8{0, 25, 47, 70, 95}

func (i comparisonPosition) String() string {
	if i < 0 || i >= comparisonPosition(len(_comparisonPosition_index)-1) {
		return "comparisonPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _comparisonPosition_name[_comparisonPosition_index[i]:_comparisonPosition_index[i+1]]
}
